POST http://localhost:9000/records/body/mail/serb@mail.ru
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "tableName": "test",
  "fields": [
    "id",
    "id2",
    "name",
    "next"
  ],
  "kvEq": {"id":  "1"},
  "kvMore": {"id2": "-1"},
  "kvLess": {"id2": "5"}
}

###
