POST http://localhost:9000/records/body/query
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "client": {
    "name": "Ilnur",
    "phone": "87623187456",
    "mail": "serbaevilnur@mail.ru"
  },
  "houseInfo": {
    "stage": "На стадии строительства",
    "houseType": "Квартира",
    "rooms": "4",
    "price": "€50000 - €100000",
    "date": "next month"
  }
}